### ISSUE TITLE
ModuleNotFoundError since v0.4

### ISSUE THREAD

**Issue by bdura** [mkdocstrings/autorefs#17]
Hello,

There seems to be an issue with the new release regarding the interaction with `mkdocstrings` itself. Consider the following example:

```yaml
site_name: Example

plugins:
  - search
  - mkdocstrings
```

The following works with `mkdocs-autorefs==0.3.1`, but not `mkdocs-autorefs==0.4.0`...
